openapi: 3.1.0
x-stoplight:
  id: ed529pn5fglff
info:
  title: PetStore
  version: '1.0'
servers:
  - url: 'http://localhost/api'
paths:
  /pets:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
      operationId: get-pets
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: test
          required: true
        - schema:
            type: string
            format: uuid
          in: query
          name: id
          description: test
        - schema:
            type: string
            enum:
              - dog
              - cat
            example: dog
          in: query
          name: type
          description: type
        - schema:
            type: integer
            minimum: 1
            maximum: 12
          in: query
          name: age
          description: age
    post:
      summary: ''
      operationId: post-pets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
  '/pets/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
      operationId: get-pets-id
    put:
      summary: ''
      operationId: put-pets-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      title: Pet
      x-stoplight:
        id: 0xz8cnognhxdd
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        age:
          type: integer
        species:
          type: string
